### ISSUE TITLE
Fitur call nya scam gaes 

### ISSUE THREAD

**Issue by itsmeR1F4I** [DARK-02/DarkBotMD#3]
Skem

**Comment by Bayu12345677** [comment]
ripai gey

**Comment by DARK-02** [comment]
Tunggu w up di yt ancrit

**Comment by Bayu12345677** [comment]
> Tunggu w up di yt ancrit

fek scammer

**Comment by DARK-02** [comment]
> > Tunggu w up di yt ancrit
> 
> fek scammer

Ndas mu

**Comment by Bayu12345677** [comment]
> > > Tunggu w up di yt ancrit
> > 
> > 
> > fek scammer
> 
> Ndas mu

halah coba bikin spam call tanpa rest api

**Comment by DARK-02** [comment]
> > > > Tunggu w up di yt ancrit
> > > 
> > > 
> > > fek scammer
> > 
> > 
> > Ndas mu
> 
> halah coba bikin spam call tanpa rest api

Stress, makan pulsa, blom lagi kalo di jawab callnya
Kejang" pulsanya njim

**Comment by Bayu12345677** [comment]
> > > > > Tunggu w up di yt ancrit
> > > > 
> > > > 
> > > > fek scammer
> > > 
> > > 
> > > Ndas mu
> > 
> > 
> > halah coba bikin spam call tanpa rest api
> 
> Stress, makan pulsa, blom lagi kalo di jawab callnya Kejang" pulsanya njim

bilang ae gak bisa

**Comment by Bayu12345677** [comment]
gitu aja ribet kek samsudin

**Comment by DARK-02** [comment]
> > > > > > Tunggu w up di yt ancrit
> > > > > 
> > > > > 
> > > > > fek scammer
> > > > 
> > > > 
> > > > Ndas mu
> > > 
> > > 
> > > halah coba bikin spam call tanpa rest api
> > 
> > 
> > Stress, makan pulsa, blom lagi kalo di jawab callnya Kejang" pulsanya njim
> 
> bilang ae gak bisa

termux-api 🗿

**Comment by Bayu12345677** [comment]
termux-api mah yg pake nomer sendiri coba pake nomer random

**Comment by DARK-02** [comment]
> termux-api mah yg pake nomer sendiri coba pake nomer random

Nomor random? Stock / buat nomor sendiri
Stress anying

**Comment by Bayu12345677** [comment]
nomor buat menggail victim

bisa ga kalo gak terus terang aja 

> > termux-api mah yg pake nomer sendiri coba pake nomer random
> 
> Nomor random? Stock / buat nomor sendiri Stress anying

**Comment by DARK-02** [comment]
> nomor buat memanggil victim
> 
> bisa ga kalo gak terus terang aja
> 
> > > termux-api mah yg pake nomer sendiri coba pake nomer random
> > 
> > 
> > Nomor random? Stock / buat nomor sendiri Stress anying

g bisa, gw run di heroku anying
klo lu bisa knp g lu buat untuk nambah fitur Bashbot

**Comment by Bayu12345677** [comment]
> > nomor buat memanggil victim
> > bisa ga kalo gak terus terang aja
> > > > termux-api mah yg pake nomer sendiri coba pake nomer random
> > > 
> > > 
> > > Nomor random? Stock / buat nomor sendiri Stress anying
> 
> g bisa, gw run di heroku anying klo lu bisa knp g lu buat untuk nambah fitur Bashbot

aoakwkw asu langsung baper

**Comment by Bayu12345677** [comment]
di kira serius anjer

**Comment by DARK-02** [comment]
> > > nomor buat memanggil victim
> > > bisa ga kalo gak terus terang aja
> > > > > termux-api mah yg pake nomer sendiri coba pake nomer random
> > > > 
> > > > 
> > > > Nomor random? Stock / buat nomor sendiri Stress anying
> > 
> > 
> > g bisa, gw run di heroku anying klo lu bisa knp g lu buat untuk nambah fitur Bashbot
> 
> aoakwkw asu langsung baper

Baper dari mana njer gw ae lagi maen setambel gus sambil nunggu safelinku kembali normal biar bisa rekam ulang video

**Comment by DARK-02** [comment]
> di kira serius anjer

Skrng g bisa login setambel gus stuck di loading njer

**Comment by Bayu12345677** [comment]
> > di kira serius anjer
> 
> Skrng g bisa login setambel gus stuck di loading njer

awokawk

**Comment by Bayu12345677** [comment]
> > > > nomor buat memanggil victim
> > > > bisa ga kalo gak terus terang aja
> > > > > > termux-api mah yg pake nomer sendiri coba pake nomer random
> > > > > 
> > > > > 
> > > > > Nomor random? Stock / buat nomor sendiri Stress anying
> > > 
> > > 
> > > g bisa, gw run di heroku anying klo lu bisa knp g lu buat untuk nambah fitur Bashbot
> > 
> > 
> > aoakwkw asu langsung baper
> 
> Baper dari mana njer gw ae lagi maen setambel gus sambil nunggu safelinku kembali normal biar bisa rekam ulang video

asu kapan nambahin fitur di BotBash

**Comment by Bayu12345677** [comment]
gua lagi nambahin data base chat di Bot chat
